---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: immich
spec:
  encryptedData:
    cloud: AgA0AdhNDTAUm0aT/VRTW59TTQlHLRaaqKTr3WXaq+FSFCjYG0R91TyNVeio7UKzZS4sR6kOYFpoH+a6MNUE1czlI4Duod7BEBJk/eCrqFURVVZcCSHoQX1EHRBgAwp+LyyIz/OMnUW3w5UitpcMBjhYQusgQs8DPQN8lE+cIiFEYj6btYjUxnbXNIJERPAezsuTXIMeGuhm4ULvscLFMikNA+4ArdCWEhpRNE25yGKFuPlYFZeRU+3BD1AJcXdsuyFs2Tm6+eTOEka4mj9QDn4UH18CP8O1YMp1RSOzu6zMqwAkRqbXhx19x+gZp3NiQWkm7ZkoQAXAdgCbNxyFEPAzeOGlxBKvrwRAapQXtDwNAgDf03rCNaMraQ/Aq7VaWM+HTkTyLCJF+Z6jtZOX8tpfhQWA71hWlOpxc75qiFLn5lKKPLB9D6IBnxPW/NJZudBrjnk1ER/PdLAQdPR3NcPYUr3GLWRJIgf47OcgUSVGd9MwzR8a+rD1SdQ1NrBU70YLV8PSyltBjSo7hzdkUQchAUqPRptYDRASkCu3hyGuQoIMb3wSactird2IhXBXChNU+G3rqYY+iEyNzhmrmLUJzxWmpxm3qEMbKHC66ftQmGY7TxqF3IW1BSk8JyFDwVS3c8+T0zCicDSuL8d1II9PglWSpe/nsF63BKkdbkORygD3ew1JNBGaMVuGKt2zzkNRkMohoWHPa4GYVdlXRdTs2LoK2HbwaV+H0rG7QnLSYtJ9ZxSq37MBQoXJicBMBPj7J5pbOLQJeXGnZi/U3Azr19HlmqX94KPwYs5iYARaWu17Jg8g/xKGMLGhJu2GZqN9+7+Lzr3YzN1P+4n8T67AIYMAoSBnE0eir+ell26yEhn2UcqJGo5AB/2vZegZ
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: immich
