---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: immich
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCyJyPo1p9+s4gw8jRO0uRN0qAB/Tzqx5DKQF2MnI8E6AlSWDsLShhxQLSX49nkWtyR9qJGtWHjFVVWgh3NWPfwTE+X5eJw1W5xobMdpyZFmu9vlIuaKR+cjjfZ9vPQgA3F0afnMjggW3djjufkusQ3ks1+gm6md/EF77sc/ZbOGQe+QOea0d3+k951tz4BFDbWpymaNfdI0Q2YVW+aFWiKa5DgtQC/bBWI5ebwjQW5sDehtiGeRWb5te/3EJm3khVQkJGFJfITd8ohIhSQ1Q76PwAuZnsqu/mIfxw171A6Yk1+lOS0MvP3gFhDR4rvuahcb+xh9L2G3ZWPgW9OwvGk+6tTnHXZZAHcZ4j0BIrbH4u2/z926HK/EGsQ3CQgYGKkZzhgzu0BZI5gxGXMjYkugolYUoG1vrmALLFoIVN762EDnA+VmQu6HVlyI9M1zZuuz6wymqSWK6322Nzy1qvJTdpyUWqQjmU0/+2gdlLHploBIxJRKLNTE9tilFRt/y9mbd36kFML2NCYWpHKkCMBsjtY64nTkle3bSTa6wq1O7/PvhbGVBK58HRm3UZOjrzUeMJV/LnTlFWV1ih4CgMGXPK6PIZanMGpwaTETwKYftaTM+tRtu7qIaOR89+BpgHXVYVHx99FQ7TIv/TECevfCqJy/3l8NOD0RLTMvzPk6rVvAH0paTJiOylOeN0bahp7VuNaIvW8URWxguUDIZQxzH6HMNoJWCjOqg==
    AWS_SECRET_ACCESS_KEY: AgAdhdcKB1S1khBBn/0UgnJFhofPNwYcug6QU6ohglDRYqX0H2WjSLF+8EomToMhP4MXief5MPEJ+b5EJrujnUaOtOswmyXC7BTpxymWagv7SyEdYZ6WVgrMEqduAsCylY1wvlgl5U02OsNb0eJgVQDyI6M+a0rpyIfNQ+Crhuw7O6Ea6JIrTTI9ImvhDiovPpqJKQHc01bYiOH+nbOGlYNrNNyrEjKKsgN6dbdJcYrWEg5RvQDP5PQhCuelEdvq0RiMjS6ej61fJkFkkg5WmX//28wU2Q6ceCMoi1tEDU19F3Cb1QzCTtUQr4Xga4lMMSuOUq+6acXD04Pfl8pru/yd8+t/GLbuCtsP35iozFH9ZBWUxAIzPE+bhK8ZyjxJl17c5tgsJvURZ/qSyFCZwtVefshcZuLjfSSmRJisBcM2FUy0V78M4E4pbD3JZjoOLzIG3ZBasqFDkISOdvTKUbtusZopQcxjHMnvhMKO2xJlM1OpSLTA2RLlXvkJuUCT9x90uAhIvMqeYQWxW9vzat51jE6zXrfyEmbXenLFFQuOJMvvTbJkKy5SVvvf3QRzctKI+AMXfYpWBB4zv8J1C5jjaGOntCHQg8qIifLSn53IG9r7snhJcS9qDEzB5TcbYddkyOTWDlj2g5OFVan9tBKIAF321ecgefqLR6urQ84itRnM81wbupRLk5ND7dtg3kemqyEWIOPRtj/PIOa0sOiuWQnFpuSyR3w4zc31NvMqTpvATpkGnNjZpBuDypP31NH1GxjcsKrj9BWOnsFxSxVv
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: immich
