---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCbRdktxJEX2eLM+sKRGJLFfpI7pOZjNIZbSI1v/vmwMAR3KGU3ED+qUGRyNHINFE+wp3roEeu45AlpXsVay+c91ZB4BuEAWXGM7NZp0ZxkAaNPvXkQZ+Upg1XiSHWZVSyh/2pCYf9cXzIkxjtu9GEolPLS1Z6CYpaYPOpJxt3WWuOmP69yTJTit5B+kI0TgGEZWWW+EIhJeRzMIqIf94moMm0hqLPmGrX/4VQrCGgQpLYjo45VEKCgXPjco5zYyO3UuUB8kEOZlZa1lq6vI5H2ich8FHYEbI/sAkCSSh+rzDVsRsjIQa58MAfUnD7TvIYXHedQfh/xNWMgSkNCNwXXBzncbVH73PYxDTrw3iYTXS0XHLOf4M2cJuCtrzP4yzHoyM4YvFGPiYwYNMPk0zgOlVCx6SHTlndajSfib3XyJu+Pntod0d0Gor6ZgAv37ycsw5POnjzb/bMm+RBtGa7XhF2bKosiTWMLQSoD3ZRj64OQCzwmktYXauGD40UId37M97NCn5a84WrpEJ1K2vuH+mTpRm+jwPAY4nLx72+0Bx1i5AxO3PWYSxadXeeqETapZkR+Ic1NySMLdHNags/gkFjXYPHhUpY6pabA1pO0A9tUaUkJMEgoJJ5OLx4oEm0nnKJ3CTR/1WAa89l7mIsxMkgXkY/6EmFto8CRNX+JL9LqStQRkpYAloPe+UodtSR4MYnGWOcnIfq+ESirGdc/EZeFnxR3C6/v8g==
    SECRET_ACCESS_KEY: AgCxfjmvihsJ9bzJ21ciy1egnCi5EVa/WyPx9i5U7AyqBxuZNLpTE1EmyhA+SDil+OR52iRV1nxZ0yNF7FpJZSwlB5tf+oO4CRRvN/Ng0AcB62DM9jiTj+zPkK6Vh5ixyiRrVLYEQGSWEE5iMFmlnI7+wPLpLUY5oSAOywpH6/K4vHDEC0btTtjDFMnfsvYZg9xBn5+EDT9jePPIjyq3JXzImdT4G7RPpghZXN78SPBwzKNJSYlSGOqwGQ25aTNSzlenOG3xmUJtVdER8V1cPUxLy/MvmqN49wy7nXvxTe9Uv1BEuU7sRnua4oMCh5vF9hOLWpPdjdJVrHivDeoh9+OQqH11lwuxm93K+lC82MRd8+BTPEeaUNJd9F4OzQCA3wf5wOTpkI0dttMd6i9tnmusDiXBZIz5fAoCNFrVMWn6xH1PFssM4/CJe9Uj7mEDfhhVRpq2XwO1xCYQaJLnF42nh52AowXNN6UX4AV20CyBPssl1UbiDzLk8mdqqHAfDIM0+wDuhY9XUXUNxi+IYNMc8m8UwzysDSC31AYBqfT5hsxfCWP2DVf7VihulEMaz5OMMOFBrUhQdVaoeWKp0NasyXBmoNQ7OGLYVUMRqocn9jMfPyYMg+PGrAXGkWxpATUMy2IlSfuQ04glr7qfGQbCyfBVtESoGOUfeauWZHhtyLnoj1l0ihT5H6uqcnASZOJVusmoanwI8sQiNuluJyqssY4VcoBqeBSDldNN07c8IqXePWqNszYsa5rnhXf+MeL7kNMhkxeFcr3n0s2oIboT
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: immich
