---
# tasks file for longhorn

- name: Add Helm Repo
  kubernetes.core.helm_repository:
    name: longhorn_values
    repo_url: "https://charts.longhorn.io"

- name: Install Helm Chart
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    chart_version: "1.8.1"
    release_values:
      defaultSettings:
        defaultReplicaCount: 3

# - name: Add node label to enable Longhorn default disk creation on all worker nodes
#   command: "/var/lib/rancher/rke2/bin/kubectl label node {{ item }} node.longhorn.io/create-default-disk=true --overwrite"
#   with_items: "{{ groups['worker'] }}"
#   register: labeling_output
#   changed_when: "'not labeled' not in labeling_output.stdout"

# a storage class with three replicas exists by default
- name: Creates directory for manifest
  ansible.builtin.file:
    path: /root/k8s-manifests/
    state: directory

- name: Create storage class with only one replica
  ansible.builtin.copy:
    src: longhorn-r1.yml
    dest: /root/k8s-manifests/longhorn-r1.yml

- name: Apply the storage class yml
  ansible.builtin.shell: >
    kubectl apply 
    -f /root/k8s-manifests/longhorn-r1.yml
  args:
    executable: /bin/bash
  register: apply_out
  changed_when: "'unchanged' not in apply_out.stdout"
