---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie-database-secret
  namespace: mealie
spec:
  encryptedData:
    password: AgAX/owhHhSAnNO9HBdgHr/HqdrdPO+hnC1rDixyd3f8uSL9QFIcMM0U+rLmCkYSke7xyUWlQtorwv0c2Sf5gXbF0vvwyr3mavEqYXdbjwfBeZLSsRiSN9V0/Mk79UIZe9p8/DJHiDEORSfTgl7Q7B/JHEDp50WLDzgTN+2nNxs94stIcW2+2W7AbgsalAB12+9ZXoQf/ZP8g4VvmMv3P+yzy+jiNdZHvPLoinqLA5dESWxgTvWOfO7NrXmWSZb28Lr0OraKJPZPCaUDee+7LnivjpEwVs+KHRPpygLwAl/+YB4jXkCWCbex+nVcQAST/P3rhK8ADHkDtoOWDLsnHd6IpdGg4FAQpaCF3opR+V/40uUe6tcPQ3i5OhLdRgRqBcvzD458YOZMYu2xejlg/naPf+s5ekOeXbJoD3pEfA6MMW0LEIbLF8Ap0rzdsmmukjH6+7CcEVENXulUq7o5+B1cKO8iqpQAepFrw81KOXMVfittfGDRiQZaiFPfCslBn8L9NrMb44ImdaEOCtmR1UBhRQ2Cp1HF6RHX3L48f13Mz37RNzqpowJ0UQpyHR+t1CqgDL8dqOo5rrwcZS3khWvh410AhdDntagluNA74D02QjIVV6tipb/W4txFUftS+gKNMqB5+EdaQ5zPN0/va6W+do5KnqWjazj7dbeH2XAcgMFMKL9tx4b6En6efaIWCutDzBXAyZk5J6s6mLN7q8XYjGeqDryId6EzEMhZteimqywaFCrCQgQu
    username: AgBBdIgjudbjKZ9cWvg63By5zY1wED6gD4Ve4ojWNUVrIpAWnp1WSot4tPS9HqUkuPCpeKdU8uh4Yl1bLwK2gPDoR0dHD0q/KnxWwyZbEgWXiuMlnR+HhAxwpG584byfKG7ZEkKQkHfRrQWse/fouqr7pr1ad/kHwVaSG8NMK/HbtlDPep9WS/dbdzyhfz4gmtBh9uJ+EdDyr0+s8JZCzPvPlwFm+9pc+JteKHMXAvE+VpAsAVojNyUUecU6EGLq3TGxm754gJK/VsWLBpDILln0IYZRcJj9cNJZnSJnJ+Hxuu1Ob8+13D7dtqOrAOiyfymOPzGCqFn7MAEPph/Zc4mKm3nAjZr7EAkBLyI4aVGHut5VQFm1assy8MYCXrbJurYfK6ykrNXenD0Ij7qVqaB67EF4jA9w0PzMtUP1/Vbyy/H++RlMSyTCe9ajhLP4xf7E8jwHQRrTwa9RvQeD/Y6sp8MFpfcyTieeGUmqeyxxhZbtJISu0d1ZX5v9Dczz8AxLHh7tFygQ3r1chSRAH2oUtV7wq6j4NImk7A8WIWh4rkcMMQy3djqUBWaueZNord8KSgsjhq/qyemm57Rxvvj0XEcQqOVS3i+mgQtik+ezoOS3DgfxryqHlLn/ommf4G+V5npLQvpT0Kr9pV/FkCYOIgADPs7+I/i240FqXCmjDXKRSyLrbc/CiYPHKW/ibkrtTzCTiuI=
  template:
    metadata:
      creationTimestamp: null
      name: mealie-database-secret
      namespace: mealie
