---
- name: Add CNPG Operator Repo
  ansible.builtin.shell: >
    helm repo add cnpg https://cloudnative-pg.github.io/charts
  args:
    executable: /bin/bash
  register: cnpg_operator_repo_output
  changed_when: "'already exists' not in cnpg_operator_repo_output.stdout"

- name: Install CNPG Operator via Helm
  ansible.builtin.shell: >
    helm install cnpg \
    --namespace cnpg-system \
    --create-namespace \
    cnpg/cloudnative-pg
  args:
    executable: /bin/bash
  register: cnpg_operator_install_output
  changed_when: "'Error: INSTALLATION FAILED: cannot re-use a name that is still in use' not in cnpg_operator_install_output.stderr"
  failed_when:
    - "'Error: INSTALLATION FAILED: cannot re-use a name that is still in use' not in cnpg_operator_install_output.stderr"
    - "'Release \"cnpg\" does not exist. Installing it now' not in cnpg_operator_install_output.stdout"
    - "'STATUS: deployed' not in cnpg_operator_install_output.stdout"

- name: Copy over database manifests
  ansible.builtin.template:
    src: database.yml.j2
    dest: /root/database.yml
    mode: "0644"

- name: Apply the database yml
  ansible.builtin.shell: >
    kubectl apply
    -f /root/database.yml
  args:
    executable: /bin/bash
  register: apply_out
  changed_when: "'unchanged' not in apply_out.stdout"
  retries: 1
  delay: 10
