---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: planka
spec:
  encryptedData:
    cloud: AgBiqclDBrfACKu3YPhWzHKblacbADYWOMrrvEq6J64kbzlLrYzpMuwd+xGHlSb3DXt5wVn1INW57Fb+6LyduqQ6l1g1GYkhBGNrjB2uAwNO+3Wf0lm2QobblnfwQwId+UqdC5R7JzhDlVSpFsRHIP5HRmMQLxEjgTxemNw/QEszfnNc4xM3pzwcwKHOsmlS0Xr/bt9xSx3a9KI3TWVk2xbEdEWfgR1XygexZPc+JY16C4V7v9GCx8fe2iQKX6VOFjMO6MLo+Zj2o50Y37JteqW+w23Uq7LNoCiiixAqwuZ6bvwV+tqVuDCVfyrn/mIskvx0Ao4MrvK6NGtecAKKkbswDmfbbc4QfT6apnKomyt30CTer41SHKvtTjDdoDrnKCbqX24oRl+g71tG1vB+SeJAwM4Di6naDP12ygewkbgE0SPFq1h9rwwhmwBAPkfj44h/atKUO7zbbqiEPEGkXPEi2VEcABV7E1FlyNvS1n9mjb0WQyfWeymCXWMZuveLaJVMXiXI6PNvSHFIu3a2csVj0J2Um1x02SpqJ8kFjx/zxgMmzy/WL155N4Na8b47qt/0XyJHw6ZkXwRSxtW3yaOXUjb+xkRXjeCHwK4jvLLx7YmoFhspvS1dfhALlwH0s568wJCP3YRxnVf4FegVkFQ+acr6q+VCG8g8AbXPZfLAauvIFLZcqPw/p9QU9nIF0nthVO7W7VRhnpi57ojqDhfarlZmT1iBeFm9fsphhOY7E83m/oJk+lO9FOjO/STMAj6DK5dNcbjd43E+qF96/SD9WpsenHpPC/3Uty/2U1J5tvLxtZG+q4bsmL3lYXRVaaodeFW93L45Fo3V3YM5/ZOJv4zmF+Fs5FFS7ESw/HcXf+tShUx5PZzTqJv0HXg/
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: planka
