---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: cnpg-system
spec:
  encryptedData:
    ACCESS_KEY_ID: AgByLSTjJqqPCRyF/QUKG+qcEhVVnGB0q5ZldXm+6G58/xmkABh2Uo0TScFzpoIR5Uk7RHZmV6rUA91urXD/6K6ZKHJsJ1IiMt23AQRn2GmCXodHuZNYX3P+cBSwpv4JbzvKldc5gECLqxjQEqbwFWS1TTOrp8a3hlxbay7dDeYnulF0Wl+mby8wSaAFd4jYnEv10zvzuoooHX8Z9lWRRcGLhCQIJVFa9gl3Z0OkdmpWfP5F5J84dlUenLZRDv/pFf8S1JMhUjvMHm0UttQNeHcz4A1RGJz/1CK6xFKVXcjIKJa1n4nhsTpZgY8sAdvt2JFYW0FhavhoG7wFVfhcApXc8Dz65tA8ycYUZ7guou8YjzZ+8+O5DSIvH2ZZHQsH0uvxrTqEvHnPcukzS2HmjwTE/fNoGbhrbhg1M1q5FJ1jSmo71gccXYn3/3uq7luwTabqxHPUtExnpGFVdC0cmrpyrNFzXOW7I+BcVWM75rO1nRdKalJ5ZHrKYh21DgFGqPGRsta7EQmhYBOE8WPyYf7nXlF39D9vedRP5POpLUFL/INW45HvPT96vhSgaOvuIVmx7sAMO7g949eLViTqOfbuZhzaEsHJAqGdIvzcj+U1nhTsXTQB/+opz7AusYNhf2C7vv2OJujjcsX9mfEs+hS0slvKgKapTrW12Q3SFcCmrwI7sKxNHYVAggkbeTOt8YbKFgDtusGp7JNndM7dduo5f4xqp/boMj/bKw==
    ACCESS_SECRET_KEY: AgAovSw+FQjxymyd5YRVLtuYgz4wWKfFTH/ZPFNa1OJGa4EaLIf/R36AjAPu8rh9HB67YyCdq4ZHUQbHJCGV2WHkKj1rfEac0d00bqZ3AXdbFgfww+Od50M7KlIDiK6CyPzukHmW7oc6mWkvZOAEufjszjdYh8oGdMzLT9CNWgwoVkjAr7GbU6nX7Rh/Yyl5g5pdJqfx7qPUY1y2WKU4RRgm0FToDFj8sL5AG3HBYtFjUWrkvuHSPlK/SrT5P+0Kwl1GEzDDEV7hj4nMkk3aLcE/OkMyNUYaXy64YFOnnNf07AB3P/p/edxrIYOFqLvF7RA3r4k/LxP9B4IEk3jWVj2I82ngfNPAqQbJgKUv5QVe7XmVSEQHYtW2uZDl639VwdfrRVMZfIMMxBFY6xlcu4I9X5SCa83QIz08LfQlbS6ebT3/HM5EkR3qwLU3d857XsHwpOMeiUF8uRhmVqqD3g7jelFn0IGzQIe0Z6QZV7F0VECcb/nJf5xB30XNxzDvM60OtYGjuB/TJTL8o8Ng7zgbIpxfqvW6v819uwRXcLJ8ukS6k4hfn3N/8cOOaXd/YfpRGj7McueaBAQyTcZqXDzSbYlwL7CU5XVsbCeI9/WqkWpip7V6wxZts3JXNnhhGQsmOb38meiZQVmYZRsG62kUkcvMTcAHjhfR4KsclA78w6LG6CvQGIpvVYw7flyxJnDt+lX00jKTqawmQp0/boD46MRIhIEsCN0Gjkib4k6s1iBHzsPXTpneLwPLDlntDt+G31hnQ3/BjaNDFF2pje+l
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: cnpg-system
