---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: planka
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC3NzmNY2INGzuQP0xRypafMcmddvBQAv/ye//O9t8y+lCzflHrO16yS/J4jdvEGJTGUiD9D9udVxaYSwYgCRTwszEvYUdbP14A5t3rw5pVyJ6MavquEQr3f0mhcmt3TgBF2IczES6A3EC0Ch8pMhdCyLbkKN3cxcJX2TnRuTZJMWGO5ZDLeZUvFBvbRViYTbrHj3nPwmUANt1wpJYpuj8L6NCBMQqMVLfHVchFbnbngpJOrtbcJ8w6Atv3tBzSF4cy9r73Fv0t6J5HWUEkO7e2hdWq4b4BXOdJrJ9Jen0cUgZ/HDWAmZjDyIp3ojaqcF2vUXd86U/SpAijzxacpOEq5OfEmN24MNn43uyl+Ditcp+tq7iFzEI3ur4gt7uaWXGS5JOCrdUoAjJ523harO+NNyaCmoYqFybGUhulAmkTxt8VZwWr62jNccqOQVmEJONiP/IbJC8p2VzvOJjDFgXEMN0Euna6UrSyNa2s/dI/ks5klvcCcm9xEKQc9lUvgen/S2+BAKlWD1lFOOxl8rsO4djrPWsP0jQvGes1nd4hThK8ceEMydWgsmjn4RT6DIb5sLHznl2N9KZFY5T+TguVXtB+z87JrxwL6WiRRr2UHVR2ea6fjw9qxgH/3RlaLwB23eRhLpsBq2ERD+qkvL4pPmz47jt/lXDoLtc+ipvW2KC2lyW+C7B87a4XtAwTrxRnLVQIgYrpyKsyDnlkxji90D9u5+8WEEFCkg==
    AWS_SECRET_ACCESS_KEY: AgCvM/dM0En2EPO01PQ7j7MBObJPa2m8ax8tPIAQ/o1edqb74CkB3Vy/IWKIPAbk+flfz98LJ3TY7Yd6BCvovitNkNz8z9Y6sfxXWQimCHrAIV7wQiwH/ItR+JtWinMasBIF6cCzGJocqzuZRB2GlL/xX4yyorYAfnY89RPEKG/VeQGlJIBZ1LLy+eg81HKTufMNXbpGky395W9ey72tWGNsDDmx+jYwvv9s6mggv/4HMTOsH7AJHsQf8PEomRXKb+dTxmgRo76BC1rxIwd4ws5aeJE9pRDbUVo7XMjhqQdxCjuTlhQgyVKFGbHBghrZECQ4nHDMvm6s0fEtuetmyj1ZacmUR8HH4bnLVZCbOsg8cUFAyJaK6xDlivn+6H7Zjadd9RjJ/NKMencqncrCSx47VW3CWhN80CRm5isucwZWUd2emWcdtWHcggkfqV9wfFlTG7Iv9SfbZdKoH5xUXqaaNBl2zXnzSsWeYHg5ODCbJl5od/XnXl6pqwPOkfTlK8eIdEvzBswwQ5OsUq9DT2cCAqKuKh1Gj7POSMNWcN8TNDxiOpIFqHquJuZGvcasMYNbzkMhNdidFu+Jtr1uVemlvFnQVSoK29LlQ85mLp0w45eptOOSY/NMU0nh4Jwfbc5686nPpU8Rrr6h4bmCun9kgRg31oGtbgqHjHZwVXtMKtI75FfRRUIKYC1pTT8tswVtVqBTbAJKCrHSlBQFAEnfCVuqFyspA9UMCEaDci1jFWxoeO/sZ4jzk7rAGOAMYFDERK9QmwErm4ZoKz9Z4Jou
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: planka
