---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: planka
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCifcP0I2H1+7m5UF37VXyRbXI2g2Iixc/90uuK2TYXMxKoG7xRKU/8dxa77Q96q5bSw/lGT71wU6vkZ7CRPB0LbO66hpscmw3v8KekYBWMJNqo/gO0mQqjORSN1hOl1pwuYd748jmI26Knwl91hUj2cj5ZLXf6l5Y/g6CNfDzyVoOXILHqTu99LchmKl8hGynp5rSuK9a/dietp3ZCZIOsTzQHcEZwUk99oE7nClSuJaloE2BRHauVlh9lTKHv+rnob1A9lBChykqOIKceYnMg75PaBXTrK4248B7KnACV7UxRqvJMLBGXPrz6EAQTYSjom3TjyjyUVMyAWGPU9aD8SHY0douZraUlxcjtILAgYQTQXOe0DcAqVCipRs+bfquWxTGlDw/M6kMDVRi1khAk3L91Y7JbXz0NtFK17Znj5vff64UwGHcwVp3ymOUdCWrnBG6lnDs/pCaBwyCrVmVwTm4SNWgpaJKNFLB3mIy9oBoNBUY+ny9JIbeFb89oaaK6Om7Hd1fdFINaOwrManoVfo0FhayOYxwSkwIbL07Ik2Z+ikRr8xbF4zC+3SdwcYA5YOL7i2/bLl/AAyFxsi8zIBquHMXSlHr/mRDjQjs5sX9iXH42/WbUBWtsI9d9BFdvNmPklfUlCmWx7SdLJloeiIWo8nnBgEVcc63YF5wzOafddddRUifme8jlou3NeQnxRUVEltqDUmjhcJwno132TzfPI/nyIzb4UA==
    SECRET_ACCESS_KEY: AgBGuZh87vQ4Vc1qfMfjthjQ3M3EXOcPTrZo3jV/ZEZD7LCyWpjEdN/RpeCr4sAkhCfd+sr8zewPFcWrwHzUgYFYZX9/JMnL/G9TtyGuNeKaEKsrCWkVJX/bZdye49iMxA4BCURLBacCrdBLmMJJBHoStOuNMcR6hbOvE6iHKlYUfcIVhTc9nmSAJdvNQ7+SWvo7BrdjGtpPVfciFAWJOk8+wbfIU5LN5NNSYX0cFhS7ruq4dD6N0T6JKiDm61dOg3WwPNvONpAIEWqSgJnIRab6D7mocd07vlGvihmts53saaYfprnRHnyOadkbI6weWJwI8p8apk4EzYghsEpdf8YvYVizh6U62HOUAg1xGpOraFnSKq6uK7U61UjFxe9H309ijkiWN+8dbjrcMklly5NWmBF5636/te5M8qtMeCC/NlU3llNTqPHqm3Fn2coQOlnpVIzIdaO5hzdHeH/qHBHfsU2l2lBGbtj7o4ME9uIzqA3yurndgWICg0dxP/0q519j3+ayXAUqQTng4TIIFs2j+2fHj53br7HjWC6klRu1OhoTNHFTxVkdnR6caNL9q37EqcJVaCaPALOPg7W/R+asQQF57F2MhDRB1JkvYR99zWp+0Jwrhny4tGCZGXKGWer0AZBSPbjryuHI1z6t8ZvHBoBJSyuhuFOjfUcb8+aNr+yYzLXcLriIfsxmbXmp5brzQ/+blpSMCFmV1+njZo8AxHCXWFZaxrZozUd3NP5jhqbOHU1lnyDXp/mKfm3kAxDhf0jY/cBsAd3MFWIR1XWy
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: planka
