---
# defaults file for database
database_instances: 3
database_storage_size: 50Gi
# define this if you need to
#database_storageclass: your-storage-class

# define users here
database_users:
    - name: user_1
      password: "{{ vault_database_user_1_password }}"
    - name: user_2
      password: "{{ vault_database_user_2_password }}"

# define databases and owners here
database_databases:
    - name: database_1
      user: user_1
    - name: database_2
      user: user_2
