---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: mealie
spec:
  encryptedData:
    cloud: AgAADAZ5i6Vcp2z/lH82pN0eDpsZ9dHCtI5DDaZMQGIN1mrtz1Dj8/JR1vu/Kyw2az3d0glgTorml10OSdMSF49xI5NbgX28kUkvCz/o7t8OxAvM1ZQp40RWfKz6HMQ1WeiWO4fzMXsZ0VuQfKWUYKUqzmQmMqRJ704gY2KgScOstYX/wWisfrY/3x6rTq1xYnRI6ltOR56jsKOLbMoTO4PuSD1W0OLf9sIIBLvbfBwaO37MJj5FsB/wyQTbPl6L2DdJlz8iq3Ii4ZeFtido6RmfdjAhjxmGXVsSIfYZ8uLnxoTdpMqiV672/Eknis0+dZGXHEu5lG/vtptOdlMKLyOHiDXwoDN94El4qUoFXwcR5Pw9UMGW726Fvfk1Wd7S/Ul46PYKBTy5ATuDE+qx6TprjBl8fSL8zVh4S4AFoWSJhBA9QODxVB8HOq0dKdj1DCMaWpmRwnvsEp1+j3DadZYg1O1M+TIYNR+0bvQY8g0YL9GO4/NMZdniYf0m2PzCjfFCM1eflwKnDKeGJ96eTlw5LGBAk1rHi5MXERl4CCTEpkmvHRlzVNOu5Yuux33Sfx5LpGI00Hz7pAkpnaBpE231kMGXCmw1F2LJwxbSAqnkcDJoLyOEwL81y5ucOtY4P7r2I/nykQgla/9V76Q08qYzblYzkcbQiSdcvqt8UPakh+AZoawQQFOjzodCIOjo/qACEVqIsdi8tSodmHwR36ihaH2xEUDt6LWW1csyfMPhz2ZknJ5WFhAXWI0+9t8BalW4D7qXCzbtFe5yztKtXmyMohiwu/QAWeND9K8I9axSzIuVDCBhevY1+Uab0KfLCDgSeXRdUMQoW9LTM9n1sUuTf8tDe6bTYD3zzVVjqQjVWqb/e9LfOHcQzOYr4wgm
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: mealie
