---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: mealie
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAWsSppJA4sb71gO7V5bDEhhyt9IV6vppY2zSrxJC0f+iGkO/+cnnqBOVxFv9f6ofSvmGGQQnmuokiTiOYYB5o9BNqEV6ytKgHDTV3a7rPIGvO/147krkvbFMJmyT2inbBYjjfqYjOJKx73tPFTDk7imd11+Ss+e29ljF2VX3PiIy5i1VSEfAlgpDfdIowFWIC6DqyRcJbKrX8WYv7A+bUIqF1c7st/YGHxHgpMkglgGgbeg9HTFKRoUSKJhi3u6DCR2u9HLevoixend4sU/BrK8+NZzuN6iboS6IpHgRkZFL9r4y6GiSlUi+UqSX+097Uter1Q5lzqiQj2mYcJDGkDsVW7Npv1HajVVmDErAkFFc5ChxWnENwUjQwaAF2s+SajqteuwBTpVoVN865+xEZxZ9/k/PlP95FDCJaF+P9Ixg6ySHnhtDX5fhIvhZryDXkO0m/udQGh4ovZCYybrjYMybfsx53l+6x++yFqEg9sZfARbwVsRN5aR1wyRIKNeXgOjVF6hBze1L93T+7n04EbbklBOciLbage9ClHu5jyywNYSFuj5+xdC2edpShoqUrDJ6Do1WQ0Lhx08Lz9EakRLEko1pOPKzQ9597wfWMhmqKnsCU1FT8jJxRI6sNy/YBTY64zeHxv2oImKxcuJwGv1N+TDKJHxek6I45fg3T5TlDanDfYRq1jrhhXozMnOMMTbSe5qrzPRAw2zXrSabKmCYuC4aTJzsAO0A==
    AWS_SECRET_ACCESS_KEY: AgBwsvIJtO1rJ+GYM551QN6w+aGl9xaD3nJsgZgFn0LBp9YayPegIKEwFVLNF2Pjk8yYSvOTgb3mie9lXPWMY5MZUVGeKZ5eWFA5cjGSHD0SGfznTmWzQh4gvqm+ssp1ZcDTrLhjVGzvJdGZP/ddai60xwxJ1Eg3xMHbOiyb2hfPNG/gm8XiSuk7+bk9TrvxmNCdZtauHIpgUfLUYSKODqRHAgAyRzOmZBNkNc/WpC0lJAPUgEzFd3Cnw6W3BAAH5rKxyvqli6kaQOO5XRGPTMN0NvoFw7Fbh19szfAMMwyd2ptu4eu3iCg7Gyo/vm4oeVcQwiB74/c/fqjqvgUPJJLGuXPmNEn+qFexHhvLKqqF3t6L+bTaRZ0ygxiT8WQ8QWtTmuT93U9jKmY/YhVoA8bRqmsdOo/HbMxwq2OAhxAC9dqKSMue2hw7PyFQeSupk0JZQTGAwz70zkNg4kb0TqUfNCF3yr3bJ4PkbBkGz/okP5+gTbuDBeLT3xeaox4EhPr2eX6qRNld1/UKwMEdMdyAASideAdtr5l7K0vYs+hhc5KTAfNUQTdaKVnbDKiH0rUKsEkh/FAHkyHvK+Wbgl9U1ckmmQRH8YF2vSiPB8JewnxK+H9P3B+htnrS746OzMjq6T3DlEQhme3InbMJSWMGeWMbJussu//QSVfgwGRTQ6lnbEQYAB2l9XkAmXGuzlcqLNomVfSjvwFIbAHKZrQUs1B+hme2xXsiS6xP4m4zTF/g+Ojt/3Ey8VFbIRMHLenm2BWsOT25xR5xb19TzMno
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: mealie
