---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage
spec:
  configuration:
    destinationPath: s3://cnpg-mealie/
    endpointURL: https://garage.cindergla.de
    s3Credentials:
      accessKeyId:
        name: cnpg-garage-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-garage-credentials
        key: ACCESS_SECRET_KEY
