---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: mealie
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCetWY1MHhDm7TXMhq/we8NqCW4zzANJ7Yz4xuq5k/lZLrb9gsgD7/4B2Kuvai8j3wwxvFKFjb5Ur7n5ME8eGP5c/B7WB5k+wzmhr0TzgMvYCjGJFa5196wxhmKHXrfSXYyqlixWPCdMtPFUmHDZNw/5BiyKQnQBLka+a0J6g0SFQO6KbvG4mu6leC1JykkCbllPhgiFaG7VGFDLN2dkIvzVhWueBiw5HjouO+7hGBllI5DX0HMmdP9Az+Kr2dBEpQGcQwUsGQpjg+A/Ibt+piYTLjvFhirpDijhha/jSEk6iPBAQTrLyPZIqL+NRmBgjaD+H4aaFHEuiwDRNUMHL2c8FICl9JFP/UQ0sH2wSZq5q7VLbs4d4z0XDnuppha52OuL0sjk6/0f5MEhXJSyIOw6iGhQO9g7Y4OGuV0rZdLsIVJroyphsB9D4h4NurUKzjvNXrz9lSX9ZZqaCHL9BfmhJc7y0jCYck2BsHzJNVhOSNctHSsSg8RseKyOee+2gt4IUxQSDLondw3DV7CdXzoDzcGXovMhJS+lLAqHNnQnaS0y5RbpPnj1M+cDVdvc42r5NMnaVJ9I2LntxtY+D/1qWCrXDS++RHLe5JJILO5TZzMHVanj+uL5rlUhCoGAfhabRABGTRbqGk/LF3sZ5/9LoCQBM8y27njjH8uKXobNvnwbpqz7W07KPxfcNWGIXjHB9t1P/Q+b+NHJvUnnaphboLRN5+G/2OkvA==
    SECRET_ACCESS_KEY: AgAXjeqow7Jfgejqo2fRTpDwiaz8NA/Qogdkt4s8RldlqIj1Z7L0p7UAfCyApYgj4JK5qeqrVLpC05S5uSrZXFqWpB4zk4BPfyc0u8CDqxWrfR3p0sbUMB+zBe4667QwWwR1x4cet8furAxwncBGY4PKcAbzt/rPMFFOTBccljwCM2TE7M93bp7MSI6q8vOjC3zAe0YVD39lsXH3NGftlXKwaf21btbc+vd780B9lD2uz4FMem2GFU5TdSjboRpqU+DXcwibznWCyXpOqbQjP8Q/YvybhgCmlGRlbnYyL1mXrugwCzoAbqLc3YwVr3Z8AmtNbRhjypFFQ8zxojZcrwn0YOGV7tj4lcrzjyFNw8qZ/GkZTp33Et2FbiuXitP7dnMRx05Yj0CU5BFacoh7JbXYKJp4DE7Aq5IYX/5blfpfv1yZ5t6SAKdcgEa7GfQrJImyShNVcclDR43GMq5zFfrYvp+n7YS0v1fH5RyJXTQcsYdQfFEAX5kvyeCoycjJ/TBlshAxVFbQuMNV/J7/UOz/5k6qCy/Ktxq/aSL1eiZQyleYB0F9fbvV+G2REgXwi49GebIdOVWU4yw47yoFeQnHSk4/iqCcHfDMkfruRkMtb5O9HYRqAidr9l/03wKGTDfc7cGEBAauxmc+iCCuSoex1u2mLgwA/4girVg0+7h9DB2lwNe5flRJjYtv9NZhp8ySUKO+Jnnf1VZtEIO5J2SQNCNW/hLDmC7DcO8VfSW3tnt+hKS+c1n76iApegC/gT1nyWON7ldzdyGSdzqvlitq
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: mealie
