apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: storage
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
