apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: minecraft
      nodePort: 30565
