---
# tasks file for common
- name: Gather ssh_user
  ansible.builtin.command: whoami
  become: false
  register: ssh_user_raw
  changed_when: false
  check_mode: false # else this gets skipped with -C/--check

- name: Flatten variable to be more usable
  ansible.builtin.set_fact:
    ssh_user: "{{ ssh_user_raw.stdout }}"

- name: Create sudoers file for user, this enables passwordless sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ ssh_user }}"
    content: "{{ ssh_user }} ALL = (root) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'

- name: Set correct permissions on sudoers file
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ ssh_user }}"
    owner: root
    group: root
    mode: '0440'

- name: Install common packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - vim-nox
      - net-tools
      - ripgrep
      - fd-find
      - tmux
    state: present
