---
# tasks file for common
- name: Create sudoers file for user, this enables passwordless sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ ansible_ssh_user }}"
    content: "{{ ansible_ssh_user }} ALL = (root) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'

- name: Set correct permissions on sudoers file
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ ansible_ssh_user }}"
    owner: root
    group: root
    mode: '0440'

- name: Update apt repository cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: false

- name: Install common packages
  ansible.builtin.apt:
    pkg:
      - vim-nox
      - net-tools
      - ripgrep
      - fd-find
    state: latest
