---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: copperforge-admin-secret
  namespace: copperforge
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBg0vUrz3cmeeDLXRBVdGHBCr+y+OR/4W346F5YjSknJCDmR8ckOhdHZLSem4O8AaWsq9d+Ao8HfA6l2qJZDkxo0a0gKMZ7vXOHx2YhyaaNaH5UvIRM1LOQe3CI9jEw9z5vJgwDR9wt1rdvQlvSNRX2cQY9MRAViwX98xhJeNBAHlBlS0n7bL3yLVCCrm8rJ2fG/264c/s+t7655GT23q3iW/OhjV1A/Ef9OXgRLdYaiS4iyIVEseSClPQmW1J+phGD8e0OkKc76RulZCmoet/EXLqoHufo9iNpaQpTz7JlD6O6cTlhGKWVFY5LjwHCPx8YP14vB2TlY20GWBf7F/dDg0XaMrDS+FBMz+rHWFOUXqm9fWtn7uMot2CVtnLDxXsNra3umh15pCwMojYRhCFBl5xqgtA7+stuAZI87nZDxd8+Dqku2t01+CPq9/tC+kZq73O6glUHTbVOvKYwSe4PmvCmR2ba+gBesdEqogHexKNWwmblxITnXmzdWUEq6mCdCSd4Uww7n6gKgUN65jAVEzMJsMF59WIE/zxJBBp8hg6jpaJgD2g6Rxcr3kzQTVOLjiNBaQ0PbVsB2Ri1OR3OgK+17nLweWupWrxc3zYspROCrscJWO/+utFptpl/Zqnt6ievCs5EpMO54HKzSgfDoZeVV/Z01figCshRys5BNbq/jtQUU2xig+v2X94fFV0ZkQzbvBhgLQB481vgPz3PVcPPrFvLLHeFJixg
    ADMIN_USERNAME: AgBWVF2OszSDp0V3jyqal1rvJFlkNNJyMpXWc6F64zVXqimwB3aVA7V4OrJ3KqFw2o1LDJyqd95EAVWx6RhDptcQhKqsFwcL75OcmVkok40IOLzoK0OFuvU0Vb7nQ4C/NmxREUjQVRdQclKp6EzhD30OkUjKAVa0zau8kjv6BM4hH92QikNG9EKLl1x9jUFZruqFsFVltX46rJ3UpB+RYga7dl7oQMxah/d/4hEUeH6neTIn2VrAJQgoy3PaczTYLVdGWtz1AxCeOefBeqTNbi72ofx2aNRV9teN9nTTINBJR8a37uyEG1sPCmuojs/mIKv7zPXwGQL5uaMvL2Xmao55Y7r2d8ekahOhH8sUNIOOjKp0BJRirHQ3XMcQn8RaowBiZhDrDj3KRiOACKn7cWfX6mup9cx0zvYWzEYF7DfdkpszL9/uLGOd7/W6eqo9Dbs8XHilZJs02s/OYV9he3aStE+GnC8VWnhrJj3yD6hfvYcIZcnpnJqPuKRzYdE8p/25mwIWbYGPqOf/ZgQKjYgzALbLFG/q/8JdL5YY1aR+6zS82ovQO8GERBx01oY8dMa7pSvMJzQ3Fyh3IgZe29iJz2syMHAEUJ5fMCYPPSiEsqa5n73FSbs2OstxyShR3dqCd40F+2fmfblbaxGW1egfkRQDTaj6caVQAOywxgY9F/TklsWvfu+08sMIYf2iEW8uLYY0
  template:
    metadata:
      name: copperforge-admin-secret
      namespace: copperforge
