---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: copperforge-database-secret
  namespace: copperforge
spec:
  encryptedData:
    password: AgAHzBqQwzydAuBduadthHp1rH4m4W0Wx71qQDg9oGkS/RE9uAQfXELAddws2/1JpmScxVoUlTnu813kkqgvnN6ODoXLye2quSybYXQk2YZsxRyXXds/Z43O90ejUXx49DIrrsidLmeHXpWZjf2NNw9asCCw/YmLhNkdbQj5vanfyhK+KUwwsDIAMfQducUFlQ/097QAci849rrPdIcNwK+d4t/YtxMExJwmkJN33m7A727V8Z55fqhiU9D5LuIbHptYz8O5YC++gvhF+E+dToiEx1t5ZZ3V/Zm9F7EzaTa+iZizHXegZpXVmDBdcaeGLi5sCXYFubW8dqqRNo906XAr7maVHE93gyr/TLvo+JCs26r2hCG1e0GyR0ezJEfHEYFriiIPPAsmjNpakQwla14GbnNSG7LSQ1CQKDvEiFXMwNMoohLgh/WnsIAVS2+fF972bRcqftM3/e/tYGrmkLeLHH8Anl80X0p8rqOVlj6U7q3W3xHVE8BF5+DtaHwom1e8IVmkJ7raxiJMWmPsv/y+kbrIa2SR3eGiJQ0gbk6fBgRzYSFRXpd7jQme886/fxTkXzQzMm89pbOk04o8caHTVEGYM+F0GxZjlyx/CGUR3nSNp56c7K+NaA9kuujZ8HUmyg+zpJdNorHQdkTP3vLA5fzA5CByVplLpK2SGyO1Kh+vVcswhOJEwbbiL2C6rbC3OJ46Q2Y+k9X6hY9JTevadNhQFvagZWG3hiSdQLZkQA==
    username: AgBukbiBYMZG++++3dVXts4Q8sZfysXYVsziAQ2c/gU3L0ldwiiDc6yw19WqcDIBTUFbnUj8QCUZTNOYog3YVIdi40eC20jzWfCZIWktuh+RiaGAPsW0L0R94T2Q5b67ZXzfN5CvVP13P7l6oG9JkNe1aRCcyUnZAcSHvQAYh/hXmSRpwg/yTEejcthe4bkJCesSGDsOQm3xNePehnLUOzlkrmE+Fk4DJp5gpTlkZ4FODqRc0L6vcf9dv9ueHmKvjLYR+azpTuQwcDgVpR2teWXmiz4LkwssG+LWddhI+d4ZGVRMdMmaNPOhWzpx+g3vyVrJs4xGed5uwnX5e9u6zbqX3TC9GZUht4oa9LXkc8m7ftJalxISrBcpEu0fC4qF+UjPGXc9t8iAMdoa2DvPGFXOdUr2oR5nAe3mRzwKDOlbV8iRiscSEG47il+PUA8TfTnuTv+2+jGpk40EzlAGizsEw6bgsFyYk8vLoZUSCdyf/GCPDr4nTxVPTHDAwwVMPvoJDSXmPjfRBzt/X8WJSThaBcALVIlCFoAJBHc3AGoKKFSYzA0EGf6+HudG05iDIJz4dm4uxsRfLziwsA2gCErXNlTWmLB1c28/CRO38jIMxUltnZn28aXBP5vGlpHmfnDcl62UpKTltDkVDI4CD2ZjJuL12nq961WMdZO//xH19CVh+7UAikvxSGr4vLft/n7HwRfyPsWCl3koTg==
  template:
    metadata:
      name: copperforge-database-secret
      namespace: copperforge
