---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: mqtt
spec:
  encryptedData:
    passwd: AgBEQGipQPy13m5w5JT5HCMh4UyoxXqufU7pp9gv590jsQsSY5xFL7aRxgIooUlcvWW8CyvgDKe/gstQLGB7HG9VyNLe99yQBMm5VzbtcBABtRbTSzUGJpaFv63UHzmuzi3965sMH8ngx8GHOxEh+cVAryFI8fV/2pAvehEoYA1Z3PEyOEnCtW2DOhHS10bhE29b+qc18ZZA8twQ7UsJOoZseeRZciHiRz8Igr38EhqZwQpthxDW0C2HD5E2B72FPBqCNshrQUmrnioYJX5HWKYQ+lXhTqDT9ON1Y9NRhJuqKySIc31nl7H9eck2sms9Zh8+4Rr/Dn1sCB6VBA08SfxVyfEEEx1QnHxczVHQo54h3HbWFvxIbv5YMXqSIPNA/OrmM70mtkfiX3G26I6gJyOGbGUafhDKu/d3YPW4U5UwRlmyytn+YUfujEn+PZENfGsKKKoWgp3mO8nvueobbhjqTJNH87pfOX00w4JoWNKa9r0TIDaD53kXa6hZ1wwzbeODUn2kEI9ZS5XqHetrszjifQI8ydM2L5K0siZMPFfukvrK8ea9bPfnIDjNQnwS98j5slxf2POfsng+L5wfmLVJgTCNsheKOhWlJ7MaTV9vURd7T8MH2aWoE2fg/7thMgFtHkLgFhAoej5GZ4hNrDXhILAu2cAor6mIH1MywWfhQm8ZOwnwKe7APPisIZVYHxKdj8fqEExCxpYRKr2IRudbir0FRjkcawlMbj/Vf1OYmMBgMfya3aNi8Xhew/q4419DKLkY9ZZnmT3ouKL2/nSCKgxW7hZICWVhmXqdoGhycslYBCzbYR44CUy3hvUFe4XYFFNzCtPQp0+78GzD+xGsJflxQq6BAauT3j/4Vw==
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: mqtt
