apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    storageLocation: garage
    ttl: 168h  # 7 tage
    snapshotVolumes: false
    defaultVolumesToFsBackup: false
