---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - velero-credentials-sealed.yaml
  - backup-daily.yaml
  - backup-sealed-secret-keys.yaml

helmCharts:
  - name: velero
    namespace: velero
    releaseName: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 12.0.1
    includeCRDs: true
    valuesInline:
      initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.14.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
      credentials:
        useSecret: true
        existingSecret: velero-credentials
      configuration:
        backupStorageLocation:
          - name: garage
            provider: aws
            bucket: velero-basebackup
            default: true
            config:
              region: garage
              s3Url: https://garage.cindergla.de
              s3ForcePathStyle: "true"
        volumeSnapshotLocation: []
      snapshotsEnabled: false
      defaultBackupStorageLocation: garage
      uploaderType: kopia
      deployNodeAgent: true
      serviceAccount:
        server:
          create: true
