---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBWrEYYIPj5FJEGhC8vdvlEzrkJoQPJFDHAbTZdAAP0+w2jX86cjeR1Vx8OsWSfGTCEVbNhY/ArHA043VLjYRMksj7xL9nQoARNtwlwJu5n7h6wj9yK7ePgTe8EKWfZ/zfB6pvq/SrszjKqiJelIksuxLXbtQRq7wFophZmM3lIIzBNgOTVtJzulvwKTiUcSWSCDKqA9EGZePA4ZF5h/XuiOT0VjL4b+TAzpo17j6cSTpdJxdICFPYKhaCqGN0PDI84PSsiaeME3lLEZsdKsjtquWcU6mqE7xWpQ9hHzzLgOKqec4xP4paN9WThs9i3ODqK0o6DjvUfOegS5PnHShr/Qrb+gv7unX0IkX/ZCs2aL3//jid+WnpeYIQaBX7AS5pPiDGY/Iz7Zs8D99SubbmeZqcz2eqK9MPnlk0zKmbluAPL825VOGmSjsIsTn2JSNrc2XNCP6otj4MWDzaD7h2aLSWmWX2cHouJXwbDiQNeNXyUQRMRj56Vr+Ie0HB9KiJn9UsUkbeo7oFzrlJkdhV5VLc1ikOeOiQUY0U2RMkjGzBqiHTZ3kHriDuO5jXCCG5Wkd7sAXg/h3r0hXk2hgpzTqunqvtmJvM0m6YkB2i4Sy/iLhdlpH6AiYxg2LvMnRu1ICKWMeomueO6WYyjmmyJwNJ2bhX7Zn6x6SOED4iyw8zbtMxY7zv5u0FDEOvERqVOp+rqPVp1iCRgUTPjQjFFuE+EnVs5ERaj+tCV177dPYPBJMyyb8/K4x5h57hN3q6S+WcFtoHDaY7ognpA0mMHviztBD0mB2GKm2N3mnN0wKEVdcDUrd1DeWYy68DUkaKhyLQ1dRhCYn24xSrdi7jx93lvERhLiSMrhRFEvIWuwWb45yAZFE22D4IC1gSx
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero
