---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA+kuVYiihOyP6aOqUsw2nKadT9jmZ6rZCmGWNuy696k3JUkVVTqZr3VlNixZCRCBQAuCfo5Rdryq3wyJfQf0h2Cy3ITjsq8Iz99AMUH5QLalx3y1UkoLxmvDiATLFX6r+LmwfG9ADXzSxDImfmcuND3NH74MpjRPPjpTl3nwQWc1ypWHPDHFJULGa5CrVMIlMS4HiPzskGfrvt10PBjkU+U277lBv1sTR5O+NYExMtbwpEFCzh7qTTRcnpP78Vw0kEoocMvtxmH57fb1bklUK61XKPU1AfYTcs3ngOWx1OOq395IIU6KY1QOusZL6o19SWt9fjaBhrPNz9F1+Tiv7jHyPzupDaoM2ZFp17eNVLsp/YLokT2kFVoeeq6GZhdWVIzA7kfG5m2BuiumhWn36OPxuvOmFa+xTUPrrebv8Mn5w5rCt2YSx9BNRoQyywtbQktopYZ1cL90r8Zqpg0GyUHneeQGISa7rtTxVpu38DYYges+SaEvgt68E3zL86nnDRrdGcRzEZjI8/NESyRc1sGZNTkzu6VlkZXvL8tK9GQP810OAut/qHJ4/anHDAIEG3KyOUC736kDJuAT+UsnweNKz1oqSZSS/xcA7KheQDfRNAh1080dNPuhdrMKN0kcOZiedfKlTYOC25YPjkSq1Qt/BUn8bvqPHgKnL4wA1lrmln90ukOodqYg4OTDXIWgPejpR6eufuNRdDmyaM/2fDwttAU7ytW+LuhlB5qJ096t9U3RQv4pUrMLL4aR/nVggLMLPd0/vixAvO1SpuvZbkNuMm8Zi+8KSxgXRpUMkj600BVWhN68k4JFWCj1uhwuzaZulXM17D3v6GQbcX5eVlzE3UfqkBjy0s7IIT6LZ+QvUZ4xD9LM/MVnf0dBNh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: velero-credentials
      namespace: velero
