---
### general

# TODO: change this to always point to first gateway
internal_ip_gateway: 192.168.2.170

services:
    - name: mealie
      dns_target: "{{ internal_ip_gateway }}"
      is_external: true
    - name: rancher
      dns_target: "{{ internal_ip_gateway }}"
    - name: homepage
      dns_target: "{{ internal_ip_gateway }}"
    - name: argocd
      dns_target: "{{ internal_ip_gateway }}"
      is_external: true
    - name: auth
      dns_target: "{{ internal_ip_gateway }}"
      is_external: true
    - name: todo
      dns_target: "{{ internal_ip_gateway }}"
      is_external: true

dns_services: "{{ services }}"
dns_domain_suffix: "cindergla.de"

wireguard_ispconfig_username: "{{ vault_wireguard_ispconfig_username }}"
wireguard_ispconfig_password: "{{ vault_wireguard_ispconfig_password }}"

### cluster-setup
cluster_setup_k3s_token: "{{ vault_cluster_setup_k3s_token }}"
cluster_setup_k3s_channel: "stable"
cluster_setup_k3s_version: "v1.30.4+k3s1"

cluster_setup_rancher_hostname: "rancher.k8s.internal.cindergla.de"
cluster_setup_rancher_replica_count: 1
cluster_setup_rancher_bootstrap_password: >-
  "{{ vault_cluster_setup_rancher_bootstrap_password }}"
cluster_setup_rancher_version: v2.9.2

### helm-charts

helm_charts:
  - name: "cnpg"
    repo_url: "https://cloudnative-pg.github.io/charts"
    release_name: "cloudnative-pg"
    release_namespace: "cnpg-system"
  - name: "sealed-secrets"
    repo_url: "https://bitnami-labs.github.io/sealed-secrets"
    release_name: "sealed-secrets"
    release_namespace: "kube-system"
    release_values:
      fullnameOverride: "sealed-secrets-controller"
  # - name: longhorn has its own role

### argocd

argocd_authentik_oauth_client_id: "{{ vault_argocd_authentik_oauth_client_id }}"
argocd_authentik_oauth_client_secret: "{{ vault_argocd_authentik_oauth_client_secret }}"
