---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-from-github
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/rawrnekton/homelab.git
        revision: dev
        directories:
          - path: "manifests/applicationsets/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rawrnekton/homelab.git
        targetRevision: HEAD
        path: '{{path}}'
        kustomize: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

