---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-db
  namespace: mealie
spec:
  instances: 3
  bootstrap:
    initdb:
      database: mealie
      owner: mealie
      secret:
        name: mealie-database-secret
  storage:
    size: 1Gi
    storageClass: longhorn-r1
