---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie

labels:
  - pairs:
      environment: homelab
  - includeSelectors: true
    pairs:
      app: mealie

resources:
  - sealed-secrets/
  - namespace.yml
  - database.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - ingress.yml

images:
  - name: mealie
    newName: ghcr.io/mealie-recipes/mealie
    newTag: v2.8.0
