---
- name: Validate variables
  ansible.builtin.import_tasks: validate-variables.yml

- name: Install and configure the interface
  ansible.builtin.import_tasks: present.yml
  when: wireguard_state == 'present'

- name: Remove the interface
  ansible.builtin.import_tasks: absent.yml
  when: wireguard_state == 'absent'
