---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgBpxUdiIeNbebZMmecs9oIqQ6pyhVrSNefxSSY7t861fgAvWjCkoWdFGLsHKBTJ+sXOvRq1rNBStTcS4BeKupi3TLhA3vwkPcC0SBnkq79rQWg8Or25FueqjDAxP9mH9GXVYnx5QibnmDGnZCaj0dDAWix42/fCeQDnkwc4N47H+b0QRAooxjlqF7XhpvUj2CWEjdAJHvf9LEyIP/TTdOEV40MJdXpjYxo1h/vYF2+LDclK9kvnXk6tkkpeu0pzPT5L6SWLAh6W0vBTIf8T/wDZ9317MZ2ZV1X/oLO9r0IlYidn4BGE60Eyq4Z5gXqZc4/I3MdqJDdhKbSeLzhPkNRu9pyPLBPg8/12HLN6UWOvOmujdP206YwLjpa5ewV7u/8MNN2XlDXljFanGToSyIvfQdFTeZESQhM3mgP+kgXTLmDXpEUED8Tei6WCmxiQp3liqTXH6YuHSTN+fkAFGyWshkZoY/IQ9T6CUY7DNuyVGJ8Z9PeDZBpv9JuNXUk60I9B80tIwJAJzPhIoKROhQt9Zowx4JXe0iMbvUwqTFfsD0J2I0smNyFuuO8pYACnSNcki8oigQFD/WO8AjK5SfPRZ2+SRlEs5V5E9uqV/qSiY6yWDok6foIb0ThW7twpe60L6UEp8WNjRPcH56VKDYcOqwrVb5Xp3PsE7CK4i7nbO9ZUEpILaKAcqeUL+ipnr8YDvaaNe4U56L2TaVEu4678AkW3sDlLW28+pjDKlU5Ag99ma1sM2iSd
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret-key
      namespace: authentik
