---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: mealie
          image: mealie
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: database
            - secretRef:
                name: smtp
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: TZ
              value: "Europe/Berlin"
            - name: BASE_URL
              value: "https://mealie.cindergla.de"
            - name: DB_ENGINE
              value: "postgres"
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_SERVER
              value: "database-rw.database"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "mealie"
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
