---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
labels:
  - includeSelectors: true
    pairs:
      app: mealie
resources:
  - namespace.yml
  - pvc.yml
  - deployment.yml
  - service.yml
