---
# tasks file for kubernetes
- name: Run prequisites
  ansible.builtin.import_tasks: prequisites.yml

- name: Install k3s, helm, cert-manager, rancher, longhorn, database
  ansible.builtin.import_tasks: k3s.yml

- name: Install helm, cert-manager and rancher
  ansible.builtin.import_tasks: rancher.yml

- name: Install longhorn and setup storage
  ansible.builtin.import_tasks: storage.yml

- name: Install the database
  ansible.builtin.import_tasks: database.yml
