---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data-volume
