apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  template:
    spec:
      containers:
        - name: zigbee2mqtt
          env:
            - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zigbee2mqtt-secrets
                  key: mqtt_password
            - name: ZIGBEE2MQTT_CONFIG_FRONTEND_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: zigbee2mqtt-secrets
                  key: frontend_auth_token
