---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      environment: homelab
resources:
  - ../../base
  - sealed-secrets/

images:
  - name: mealie
    newName: ghcr.io/mealie-recipes/mealie
    newTag: v2.8.0
