---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: copperforge-ghcr-pull-secret
  namespace: copperforge
spec:
  encryptedData:
    .dockerconfigjson: AgA9otkQabf1My4PIplhhj7GImISHBPj2NCv3XW8tiQM7SLO/LowRrgxZfGpTVaXGNkLkBqlWZ7MZgx7VtfI8SLAfcFnhSAUACjIjSz5IGHS5ngfOGxHadnjOeD8y9veuxPARmxWhWkXXU2kJeiM2Lcfwzc4xaNEMBwM7UjxvSF4HA1OChRGz9DdsLEo1gfUnqhNujOioE5pY1agE4hIJQJ1qkvnJa384RKf3hWn/fViKnHmx9HDPurmnFfVyBMKPF5RYLBpTh3ppkUKgyzijG48g4gY7LSeivOevoLEVcp+tkObh1K7BXnZAkJYZ09szwH7zIA2IBk25GZjNbM+fHyonJcsgPpaYQQ+gNPhxNkcTpbAl2tEUdDqtq7pP3r3Rwa94iRygKTCsXqcF6cygtmKqKsW9M3yEYma7S4uPZgEwAAveWlceZY+ozxS7gOUaoMD3cscdsUD/DUdv/+KRt5z9q1slFKc5rhzRCdXGbvG3dw33cRGGAdg8HY9FMJ6/LiFS2QNhnHTl/o/coFIRVOZHmK/GGVFliWM3S+cvcaPWC3b3wDirWms2WCtTfU4e6HVkv2NR4dIgIQaGK/LNxQw0azAhMQ+AF1P2x69400zLi4skxECQI0Pj/G3M5S/FDSlmmYkGo9cj2BFqKM5aS/MG6Fs4bM3OW9NwSyqUClaeKiZfGXyBUAVLMk9or+gJBw+7FvlHEzVXRQaZwhGuMfsq6EB57j4sHb7JQimYvXYXh52/F/bZovFs6EHmlQm++smyLrXFbQBykieY2T3LWy2QDIvd2PLe7+rPjo4jmj6ar5HMNfvbjlJaFisQmRM9QBujNvohjd6LOb2XEv4uB/Gwd3vlxxFof50SzHvhL6IX3iR+U0o+GmUDA==
  template:
    metadata:
      creationTimestamp: null
      name: copperforge-ghcr-pull-secret
      namespace: copperforge
    type: kubernetes.io/dockerconfigjson
