---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: copperforge-admin-token-secret
  namespace: copperforge
spec:
  encryptedData:
    ADMIN_TOKEN: AgBVfuYdhfALKPcA4eW5wUYm3LcQAgjJlOSGRVxK2yK8ZqwyC7Oam0/5fmchbuMtHs+Fx2vtMyx9cM2roV7vpfU2ASTirQ1r2cb8uC6C5re21CEoXYd/Q0ECElesnSwuLj0aHghC9uFhJfYE60tk3eV9wfQxW0cDd+Ocz5rm7Aj3jj72nLb3HsIv2Fi1w3Mi0Xbs611dZEphr5iWVwIcN4qDgDFrEraBZGEDNnSDt9JowBmXxJBl0+f1sqsGMe2/mIB0QIvgghbTuu/lTewMSdAIb4UBGDyWSAx/41iUaiXJutZbqw7vUh+UHs7wmUj3PdEYKCTzWSWH3llLiHh7VX83Po2T1nZpp3Fca/TGnfpLbjPUxNrOeoYzQzkNxATwouBVADgxupTSyaTx8WVBvjjH2fJ9jN1KXz0MObkLDQJvP9hv35V6jhNrQ55vsl0dx/2aaflOTG0E/sHLrEaneT2/MEgd3RL96/gVU8lCnFkw8aL33p3ap8kx/HOitqkxWfBXKWWTL5TJIJi2wrtUaAwqj4VLLeEGeqaMjOyqD2dHFDeQzAnzV1w/OJOl+QVcy3Le5BxYLTwTIRUupVWD8NuzwCpXwDGVp2d4YEMe3OMeyUiyds0GjUa8wRcrh680o43Dzl/6ZI3XBa4udgWqyF1+TwWlDJxAPnLrn/rMyFdghzMJOmlQJCbNuOc9lX/GirJ5xBUTH/GWub/KLpSEx12NVBlE3XEVjqVzif3iSdRmMpInevR7sN62
  template:
    metadata:
      creationTimestamp: null
      name: copperforge-admin-token-secret
      namespace: copperforge
    type: Opaque
