apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: copperforge

labels:
- pairs:
    environment: homelab
- includeSelectors: true
  pairs:
    app: copperforge

resources:
- copperforge-ghcr-pull-secret-sealed.yaml
- sealed-secrets/copperforge-copperforge-admin-secret-sealed.yaml
- sealed-secrets/copperforge-copperforge-database-secret-sealed.yaml
- database.yaml
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- name: copperforge
  newName: ghcr.io/rawrnekton/copperforge
  newTag: 0.9.0-rc.3
