---
- name: Add Sealed Secrets helm repo
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: https://bitnami-labs.github.io/sealed-secrets

- name: Install Sealed Secrets (adapted as adviced in the readme for easier usage with kubeseal)
  kubernetes.core.helm:
    name: sealed-secrets
    chart_ref: sealed-secrets/sealed-secrets
    release_namespace: kube-system
    values:
      fullnameOverride: sealed-secrets-controller

