---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: planka

labels:
  - pairs:
      environment: homelab
  - includeSelectors: true
    pairs:
      app: planka

resources:
  - sealed-secrets/
  - namespace.yml
  - database.yml
  - pvcs.yml
  - deployment.yml
  - service.yml
  - ingress.yml

images:
  - name: planka
    newName: ghcr.io/plankanban/planka
    newTag: 2.0.0-rc.4
