apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

labels:
  - pairs:
      environment: homelab
  - includeSelectors: true
    pairs:
      app: authentik

resources:
  - sealed-secrets/
  - application.yml
  - database.yml
  - namespace.yml
  - ingress.yml
