---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: authentik
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAchyHgPNiA7BtHF9qDIb+ZXy0J3vuq5eQXL0oP7JZ0noFBvcomdQUE30R24qCEDwcl4TeuUGyyzSUzmSqJ6JJYFfAy5sDC9MmDnOsAkICik/bk2cVy5q8vgbH3lAj9iOZmz8bt3oo9fGcM6kDVSFMCjWIvFmU94zA4LsdsH2GXU0zp5ZkDBxXYzDMW2GZEhxegSWu8DP6fpQ0cerbZraypU97y4dOFJhQQ4Zss4ALaqVog7bWJqJgZ3uB5VpcnJZEOb8qUFB0KRzOCK5eYoDITsl0IJFGRNCMnX8hi43wbkeGBwMntoUmnwwmuUO3Lu5FV0wk6iK7QOksGxBeKWKCT4qV8g8gqQ+2OlRklLhOz59djIS0hYwsNIL7H0+SEaKjjkILhE6MUehPgAJMlR8k2DJoEb+6Y87S3x5qM/r8Un54j3o9Iiyvl9vNuRPmiAvEsWEbTrTurwZBWRGylr35/rdSXzFShbGa+nX8TtwLGrPqg/kGrnnmAY/0wJhkmZUpMXpZi+qDeRUx4QZ1kIz4COxgkY2DfodZaN/W+l/RYslGQRUUch241cJUp9+k69UZlQOA5HLjl7IhqNvtmEw7pRR9gmqd2hWVFTvk+xfO/w9n8USMq0ZnU2FLdfwZsfXnSiEuiFRoCcxMAeoWdfAFNHoMwqSJ39KQMEogI8W6N/kq8qyGrPUFGiPq5mb+WWNLqgoqacXphNZ8G7STDAOvaqLsOkkQ4RyPjMw==
    AWS_SECRET_ACCESS_KEY: AgBHEFSaA+4oNCza1IW3wTtBqEbLQsIBuSUCaapqJfQbChuQu7fO6qvm0xAlHp+284bJ7mRMKx3hLmF94oecXHRgj8hMbZ0LUfheVjtSxkgO37Zv/wqouMsBjNQlRge2lewFQfOU3PBc0/QEkNOZQxi+fafGWwroZ+Tikze8bVxqpA9M9Fi8HaCu5cQqWOSd5pkOpgwzxJGVlqebLK28dlim7Po17h23jDF9lPVFjrbV5HUYtwvU+T0dZeO+wbOOZ4iFBOB7C6AE92CaWPupOw33EM8rhbiotBiYGgVBo+pxWVkHmKRYPmZ4sBC92nFhEBhjKOycg9YpGK/au9EK6u1h1f2vbuap1WbhITsBcTZDT3feVh5cPnwVxhuDbiLwQhbxcLAWzSD+2gV/EUrpFvVl544g/I9ZILdLg+EgKaQ57P9BLV0d7ZvLWndN0xS3MkDarQAgfmLIoKs7cEpT7TIDPhhYlCllHEarFK6RUh9FoCpXwYJnK3KjAeLMIuF9LNzjMCM8ZrNjVSXN+iAnu7UkmMRQwhgcf5d0eu4oCFM9ATQkhTzMjOUTk9tXgTabbq3LkJxFl4tf4X9L4nf84UtOQJfYqdMxpR9HL0H4XbyFru/wKwQH0i86qllwa6PEKPjv1I1TQB3UjF0xZzM+wI6LEXK2hfJ5iy40YJxqmRxpxYUvBjLhP40U1uCpzthpnpumaSWOyIbOtWUNTzFVstjKaPpCAzw5BfFNzPCoyKDtLL/CgTNaZQ+1+kOu3vs7+xq0kXcPzD0Jp5O/yvagdvhL
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: authentik
