---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: authentik
spec:
  encryptedData:
    cloud: AgAP/rOgRxzXPXS17efKvYI0SUQ+xfTXAETy2VceDLQXk/cuG+dKcuC3UCQtqV4SlOS4rDVUexQ0UmS26IPgjPguOPeCZKAiyZx1Z+8S16A2K/uqALcBboUOdveexpiURRMUSjsD2YdaxcnyEc2mZjkjQ6YSHfQ8c2Y9yeepBOmX6DEoaY68eho3Q5PcoyaUeZKM5qBabk7POQAKVOzA9DkCO5lCVBq+rxyEiC2ZAZIgOtNtaUrj/Cx6bUKfp/r2NRjqe3ECEDpzF3g5PrErge4Rrjrn1vohmffaCaXSHbM66K5+aKZnQcovC+cIrwninCyZOddabAGZVHgmTa7RcqUeSngXwY9oVUkZ5gP18vEeTfghXsHSXNegbrqgQsWUW5V0HM4cQ8XjkEIqweiZ+Bm/kvP+93U0T4+P7FHONp4q6t0X8JzP+ZXlhWwjUVzexttsmMPC0IXKRvT/1HkMcyXVAABMXm+BvE3QHjrLv7CvEoi0kwgqjDjivcRmll0GFxsAnlcCNvv6aI9WEGp8bzY+/umwlI44QghJNZUyGoFcP6DcErioWGW0uE7FZ+SF8eZAzr6aOi7weOWJ8Q6oMjDJI1rA9wbl/4AGIo/htR1p1ljsFgF+lt8YUPaS5B77YgomXhUlKZulc/4dzetS4rUyhQYNP3Q4DdDl5hoYYz24w5Vy/+QkQiSCMSJ3KqkD3HVMGAuoRoKWBc3svvjqGpTTLX7llEyuXE12/sbeYah9hGANjQEuc1twnYB2WiARxEYe1V4jfPL6NOfoupj0GawbYpzWL55uKbUdBkZAepWrglt4vJhKJzdANTyY59XwdOB5zXBMwK+4Y3ixSt3zuY0OmLkeuvoOM6bWs0Zd+gQp3WQLy4/lV96tHdEFHcgT
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: authentik
