---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBiBYbs64ZsJE+Dz1/VBmfn5JdrFdKhqxLAYbi0aq41YfkGtES51QBupNcYmlJ97zNIww5enF8sSXoOsMfXYYHyGNT6ckuadT7HErgpEfl7l+R98EynJILTd3NNVLJiHNvN+hku1HwB/PM01Jq5ZCZJs6nbj2CtqJremsGi6yB5Ut/Fj78dbBXR447NoVdW6vUatnfjb4CR1yMFo4xYbOm7cqN2B+YUaBcrwKGVZKg/YpEi+OgMtkU0Uqo5IYG+dX8UtgB4PHdFjkaPP09wxMHP0FMi8E+0N0K1xYuayoHkawCY7xYtSk0U8OPQuyQ/1CrZPiY6QBBtBXsvhHG+B27NW0g6C4kQeK8O3PkHRfNhJZd9XsRSPcPag+U3cVtvVKN8RAtGBUlOdFXwjWgMZ52UOo039+PPk4ggm/7gfcUuGm/OdbzxYH7oFqL75tWfiOeFQav51Jz2THIPLpZHEwKtUEervf8O4bm++HCojJTek5sh0jN2wIqd0+Z9ZnN73SlUl21m89e8L0bwnggfEXpjyUKlzeEgRXiiDMrNaj/APe9ZCiRKjnkPZHkdlwtCcoY3OcAarBt1NwglppxvIbv6QxPusi0cSHAf+suXaSYxOEn8Z/JmP1YrXHH0JeikxVYGRtRmX25RzM7wk8R9kaAtVViPUvc0rmmrbuUUGt2YdELqQBqEkOZkz0TRKn2TOkc1yZjfoEFhh5g7Hc6i3eWjNuypd78/3PhZ/w==
    SECRET_ACCESS_KEY: AgBvmoQDFf42UqH5dp/NIOQmeEhoPnrM/y82ZGyA3ZP9jw4Bf0Y+9z98ruEbPGjI6CV1/0ndGAchTlVOvridkAgr2IOjl7Rif50qQYyVulfHJixZzU5az5xJ0ZM9qJ06a65/eppwJ8pJ6HtXqr9Gmtwu5Jsiu20bk4ZdjWdZo5r0eAVHGdSpAb6MSRuQxABUqNoxfRyTD63QAbZMoI58MLq1DiMkHQpW9CYz0mGAFFiytfW8KquC2VjHygdS4JTJeclTsvmtZLZR4cj9FYx4XFQT4PwE1tYK0hdFqpNTr/GYkW1xHQwINHJtsJQ7UDBQZC3h/fSeF668Z8qTm5VCaVtqo688A+jYb1/iHc1MF64IqZBksHUtT0hoPnjNeOkEnVjgGY3ShZlcOpA7FFiskwCRmjjInTEIsN6BVvAJDbfkPXEILZi+zNpM5/J/L1LqtvYD0j+WEscHWtJXkS6wNw9kyS7oWfynEhvVEpwFCD8FCq/hGE/gNkCquKO+uOzXA8raVVCW+UsGLX2QaLDyqvglhyM5R6ESBeCgfkLEbdESDfqWGH5xZTxyRd3SOhDI8SNAH9+J4BsH8e6L2q3z79MwzCgzxQ66RYJGMKSf3tnGqvxSt80dbKrS/JG4NwuE8VDdSvbblidXAqwpArnxbGs9xGxMkNk9E6UYWC3QxbRceDFcbiPpH1bmMd+usCPJS7G5pYLgNhiTyetlcSMZzOBYjca/G+xzBKYn+lEmjQjaaBOk2KTo1NwSUzgqn7oX2AeVWkc0meUOIguB/OjQkH/Q
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: authentik
