---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 3
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-database-secret
  storage:
    size: 3Gi
    storageClass: longhorn-r1
