---
- name: Install Base Configuration
  hosts: homelab
  become: true
  roles:
    - common

- name: Setup gateway for proxying and tls termination
  hosts: gateway
  become: true
  roles:
    - haproxy
    - certbot

- name: Setup wireguard tunnel between gateway and vps
  hosts: gateway:vps
  become: true
  roles:
    - wireguard

- name: Setup dns records for services
  hosts: dns
  become: true
  roles:
    - dns

- name: Provision Cluster
  hosts: argo
  become: true
  roles:
    - lvm-setup
    - cluster-setup
    - longhorn
    - helm-charts
    - argocd
