---
- name: Install Base Configuration
  hosts: all
  become: true
  roles:
    - common

- name: Install Certbot with DNS validation
  hosts: gateway
  become: true
  roles:
    - certbot
    - haproxy

- name: Provision Cluster
  hosts: argo
  become: true
  roles:
    - lvm-setup
    - cluster-setup
    - longhorn
    - database
