---
- name: Install Base Configuration
  hosts: homelab
  become: true
  roles:
    - { role: common, tags: [common] }

- name: Setup gateway for proxying and TLS termination
  hosts: gateway
  become: true
  roles:
    - { role: haproxy, tags: [haproxy] }
    - { role: certbot, tags: [certbot] }

- name: Setup WireGuard tunnel between gateway and VPS
  hosts: gateway:vps
  become: true
  roles:
    - { role: wireguard, tags: [wireguard] }

- name: Setup DNS records for services
  hosts: dns
  become: true
  roles:
    - { role: dns, tags: [dns] }

- name: Provision Cluster
  hosts: argo
  become: true
  roles:
    - { role: lvm-setup, tags: [lvm] }
    - { role: cluster-setup, tags: [cluster] }
    - { role: longhorn, tags: [longhorn] }
    - { role: helm-charts, tags: [helm] }
    - { role: argocd, tags: [argocd] }
