---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-garage-credentials
  namespace: cnpg-system
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCkM+8dPDeJhc3TdXqyeCbaW9we4XsiXJvuwEo3vz+kzOMvFeEVlAOVEYg1SunggRmqX06D+doAqbcs5J+bvgdlL4mHBh0Gl9lE7tRUTUcFV2cAelzWWaAvajhl0pmmHGqT+hOAutFxr77V5veJiR85yqulJ1N89yP+85L9wN5I67Kz7a0KIIOzkdIPktDZjthrs4U55qTosQcOrpuzwhXydOay05yxrWtnj/JuByUDKZUb76e9BZQH8rEezWMy899vUHV4BqUQhNA2N6yJNjw1fNDEOIxtLNPfGCU3C1ewHw0MjkwdVKHNgGfJAnOieAe+cQvc613vAPFvJq/GCZxjaG2ajrmcjm0W0edRerL0+bRTjQOUKqh/qSnFgr25krpbEaVuS66x0KtWELfUHKlw4QZAQgX3RJxdLgYZw5dq3VNqiQuWIvHU2XvoaPjuxpJNORYwd0UgKkAIUtfSOq2tOCbVT25yG6pc/3N1AFr56hAHGZ5+NuH9MuXRzJKLBBjesQwozWN772cnYaFFZxsSa7Y1PTO7dT373KRuvMQXX3jmzowDExrA+viF0mylwx8R/ttfaIsYQC+up7mgcM987ovOzcKTFJdv1Y+R/iSG1I/Z67HRPsuKZozSUhE8turIfNRWpyl9G9RxcoCfJdEZdOA9VYs1xVmx+qkqmqRcKBRG7Vk9HDM7MQ/+YAC/xDTCY3zO/CpvH2X87S6bcdivvCQvr8LwDQJvqg==
    ACCESS_SECRET_KEY: AgCHJ8a6Vlaiv0SubYl/z3pXqVk5gehP+bpAjssjXo+fDs7jICV3R5FbupoGq2+5NwIjtkTihnfgZFqow8lq8NKNNQw0ZFhZANe+Ijca+tuY/L6gP42LvX1StXDCIBCkMm1p2QpgGhkuVR07UKB/6GgWkPDeg3OFAQplQhzPKX1894aAYGqKaf8sEJaWd2og0Y7a8ZGFB1o2RtzHnj7Xf4eHdbO1CntZB4l4grnjrz91TeTRz0oxXzl48RDPk+zM8rK787c5x16iqBn73wwZMJnQjEPuC0eyCBvL1/V2pZbIY7MpmXNT2Ov5IoS70Q78/xz9xEDYRfGhXxf7/2xjfLSbs8P0/UIgKkaWobH34zNuYzs5Kj1Ok6atWCvtmH0m9XZ4Y8OGyn+Uj1nkLABxoe3oSwhFO83dEV7OFGbLhOTU7u1RyejGGdEixCXvYIVrajocb+YiHqh3vH17sDm3uUFMIxjULcCdat0ApfTG76W4DUmTfcz92yGA7XuYL+cTqnCE6a3gbckS2bjtza52bsYvO6cugYv4U2IdlzCh4plZMcXB6bNlzN12VDfaf5CCw/CuvQmFl39YK9E6g64xXJ7J8Cc5trsJzI1Guhb8FpxAvz8c8jzrDuXZv3KGCsXVh09uED51wjmQkkV9mz5yc8veENs93zRU1vUuL6dKKCVu6hNo6s3bhCD0QmOS+W/Wo7QV1Uc1qCu7ZQVKjWLURsw2eZmi7+Sw8vTOGvmZumBe0kYbD7n7em54kOVgeFSVO1JoFB40kZyaeH1tFjiLEMeX
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-garage-credentials
      namespace: cnpg-system
