---
- name: Copy netcup credentials to the server
  copy:
    src: netcup.ini
    dest: /root/.secrets/certbot/netcup.ini
    owner: root
    group: root
    mode: '0600'

# This will never be actually run on the host itself, it just exists
# so the directory and config structure exists
- name: Install Certbot on Ubuntu/Debian
  apt:
    name: certbot
    state: present
    update_cache: yes

- name: Install cron to renew existing certificates
  ansible.builtin.cron:
    name: "renew existing certificates"
    job: "docker run --rm -v /root/.secrets/certbot/netcup.ini:/root/.secrets/certbot/netcup.ini -v /etc/letsencrypt:/etc/letsencrypt --cap-drop=all certbot-dns-netcup:latest certbot renew >> /var/log/letsencrypt/letsencrypt.log"
    minute: "0"
    hour: "3"

- name: Copy new_cert script to /usr/local/bin
  copy:
    src: new_cert.sh
    dest: /usr/local/bin/new_cert
    mode: '0755'
