---
- name: Install Requirements, this is mostly just docker
  ansible.builtin.import_tasks: requirements.yml

- name: Install Docker container and setup cronjobs
  ansible.builtin.import_tasks: certbot-docker-setup.yml

- name: Install cron to renew existing certificates
  ansible.builtin.import_tasks: cron_renew_certs.yml

- name: Install cron to renew existing certificates
  ansible.builtin.import_tasks: create_valid_certificates.yml

- name: Cleanup unused certificates
  ansible.builtin.import_tasks: cleanup.yml
