---
- name: Update apt package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Check if Docker repository source list exists
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_list_file

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: docker_list_file.stat.exists == false

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/raspbian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: docker_list_file.stat.exists == false

- name: Add Docker repository to Apt sources if it not already exists
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/raspbian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: docker_list_file.stat.exists == false

#TODO: this needs to be a handler
- name: Update apt package index after adding Docker repository, if it was actuallly added
  ansible.builtin.apt:
    update_cache: yes
  when: docker_list_file.stat.exists == false

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
