apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: &repo https://github.com/rawrnekton/homelab.git
        revision: &rev HEAD
        files:
          - path: "argo/services/**/kustomization.yaml"
  template:
    metadata:
      name: '{{ .path.path | replace "argo/services/" "" | replace "/" "-" | lower }}'
      labels:
        cindergla.de/service: '{{ index .path.segments 2 }}'
        cindergla.de/type: service
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: *rev
        path: '{{ .path.path }}'
        kustomize: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - FailOnSharedResource=true
  ignoreApplicationDifferences:
    - jsonPointers:
      - /spec/syncPolicy
