---
# handlers file for garage
- name: garage | Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: garage | Restart garage
  ansible.builtin.systemd:
    name: garage
    state: restarted
